### ISSUE TITLE
Suppress M1-8

### ISSUE THREAD

**Issue by sglewis100** [jnweiger/led-name-badge-ls32#13]
Love this code! I have a LED badge that I am wanting to use as a notification mechanism on my Mac. If new mail comes in, I'd call you script and send the message "New Mail", etc. Unfortunately, every time I send a message, my badge briefly displays M1-8 and then the screen clears and it works perfectly.

I'm guessing it's not your code but my badge. Can anyone recommend one that does NOT do this? It's purely cosmetic but frustratingly annoying.

**Comment by s-light** [comment]
as fare as i know that is the normal behavior of the badge.
but someone with windows and a badge could verify if it is the same with the original software...

eventually the hack from #10 solves this?!
( i can't try currently..)

**Comment by sglewis100** [comment]
The hack from #10 seems to solve M1-8 from displaying when you turn the device on, but doesn't stop it from displaying when you load a new message.

**Comment by jnweiger** [comment]
That is as much as we can do. Anything else, would require changes to the firmware. Closing here.
