### ISSUE TITLE
[featurerequest]  restructure for reuse

### ISSUE THREAD

**Issue by s-light** [jnweiger/led-name-badge-ls32#3]
would be great if the script has the form of a python 'module'
so it could be easily used by other scripts
best case: be installed via pypi :grinning: 

this would also mean to restructure & define some module-level API -
after a first look it could make sens to extract the real upload functions into one module
and the fancy font and bitmap things into another..
(the second one could have a [classic \_\_main\_\_](https://docs.python.org/3/tutorial/modules.html#executing-modules-as-scripts) for the current standalone/commandline use)

(common tutorial about [python packaging](https://packaging.python.org/tutorials/packaging-projects/))

**Comment by semaf** [comment]
yep that would be a great future!

**Comment by jnweiger** [comment]
needed for https://github.com/jnweiger/led-badge-44x11/issues/11

**Comment by bensartori** [comment]
Hello Stefan, I did some work on modularization and Jürgen just merged it. It's not a pip or pypi package, but you can now call the functionalities (create bitmap / write to badge) from other scripts using import. Maybe it's enough for your needs?

**Comment by s-light** [comment]
thanks for your work!!
i think with this functionality in place we could close this here!

**Comment by bensartori** [comment]
Hello Stefan, great, you're welcome. Thanks for completing.
